apiVersion: 1.0.0
metadata:
  name: order-management
projects:
- name: gateway
  source:
    type: git
    location: https://github.com/rromannissen/rhoar-microservices-demo.git
    branch: crw-test
components:
- alias: postgresql-customers
  type: kubernetes
    reference: postgresql-customers.yaml
