apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
    labels:
      template: postgresql-ephemeral-template
    name: postgresql-orders
  spec:
    ports:
    - name: postgresql
      nodePort: 0
      port: 5434
      protocol: TCP
      targetPort: 5434
    selector:
      name: postgresql-orders
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      template: postgresql-ephemeral-template
    name: postgresql-orders
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: postgresql-orders
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: postgresql-orders
      spec:
        containers:
        - capabilities: {}
          env:
          - name: POSTGRESQL_USER
            value: orders
          - name: POSTGRESQL_PASSWORD
            value: orders
          - name: POSTGRESQL_DATABASE
            value: orders
          - name: PGPORT
            value: "5434"
          image: registry.redhat.io/rhel8/postgresql-10
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - /usr/libexec/check-container
              - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: postgresql-orders
          ports:
          - containerPort: 5434
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgresql-orders-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: ""
          name: postgresql-orders-data
  status: {}
